In [1]:
from nn_model import *

In [2]:
from dataset.Facedataset import FaceDataset

In [3]:
data = FaceDataset("./dataset", 0.9)

In [4]:
data.Xtrain.shape

(4109, 10000)

In [5]:
class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.conv1 = nn.Sequential(nn.Conv2d(1, 4, 3), nn.Conv2d(4, 4, 3), nn.Conv2d(4, 4, 3))
        self.pool1 = nn.MaxPool2d(2, 2)
        self.conv2 = nn.Sequential(nn.Conv2d(4, 8, 3), nn.Conv2d(8, 8, 3), nn.Conv2d(8, 8, 3))
        self.pool2 = nn.MaxPool2d(2, 2)
        self.conv3 = nn.Sequential(nn.Conv2d(8, 16, 3), nn.Conv2d(16, 16, 3), nn.Conv2d(16, 16, 3))
        self.fc1 = nn.Linear(16 * 14 * 14, 2048)
        self.fc2 = nn.Linear(2048, 1024)
        self.fc3 = nn.Linear(1024, 1)
        
        for i in range(3):
            torch.nn.init.xavier_uniform(self.conv1[i].weight)
            torch.nn.init.xavier_uniform(self.conv2[i].weight)
            torch.nn.init.xavier_uniform(self.conv3[i].weight)
        
        torch.nn.init.xavier_uniform(self.fc1.weight)
        torch.nn.init.xavier_uniform(self.fc2.weight)
        torch.nn.init.xavier_uniform(self.fc3.weight)

    def forward(self, x):
        x = self.pool1(F.relu(self.conv1(x)))
        x = self.pool2(F.relu(self.conv2(x)))
        x = F.relu(self.conv3(x))
        x = x.view(-1, 16 * 14 * 14)
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        x = self.fc3(x)
        return x


net = Net()

C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:14: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  
C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:15: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  from ipykernel import kernelapp as app
C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:16: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
  app.launch_new_instance()
C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:18: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:19: UserWarning: nn.init.xavier_uniform is now deprecated in favor of nn.init.xavier_uniform_.
C:\Users\AndrewHuang\Anaconda3\lib\site-packages\ipykernel_launcher.py:20: UserWarning: nn.init.xa

In [ ]:
train_loss, test_loss = train_nn(net, data, 30)

46.581329345703125 47.63868713378906
47.88955078125 49.713558197021484
49.950888061523436 48.525638580322266
49.45524291992187 48.30742263793945
47.23448486328125 47.66364669799805
50.67836303710938 47.60847854614258
48.68849487304688 48.47117614746094
47.17344665527344 47.58191680908203
46.01693115234375 47.5078010559082
47.92725830078125 47.86488723754883
45.767974853515625 47.858272552490234
47.163702392578124 47.61302185058594


In [13]:
train_loss, test_loss

([2976.367578125,
  3360.21875,
  2945.294921875,
  3026.357421875,
  2890.7724609375,
  3150.04296875,
  3223.194921875,
  2931.409375,
  2947.331640625,
  2914.8140625,
  3098.70625,
  3040.109375,
  3024.859375,
  3041.9966796875,
  2996.381640625,
  2742.3572265625,
  2956.5109375,
  2982.2671875,
  2956.377734375,
  3301.625,
  2768.1705078125,
  2959.140234375,
  3287.56875,
  3010.1693359375,
  2914.717578125,
  2962.498046875,
  3029.889453125,
  2943.73203125,
  2766.458203125,
  3066.5255859375],
 [3012.837646484375,
  3164.279296875,
  3162.631103515625,
  3086.73193359375,
  3067.280517578125,
  3152.29736328125,
  3196.489501953125,
  3029.4638671875,
  3013.360595703125,
  3098.23046875,
  3016.690673828125,
  3029.98779296875,
  3012.428955078125,
  3077.5419921875,
  3063.032958984375,
  3079.11328125,
  3014.6025390625,
  3013.127685546875,
  3016.1552734375,
  3012.30078125,
  3016.716064453125,
  3014.134765625,
  3246.844482421875,
  3039.6767578125,
  3014.99682617

In [14]:
    train_dataset = TensorDataset(torch.Tensor(data.Xtrain), torch.Tensor(data.Ytrain))
    train_dataloader = DataLoader(dataset=train_dataset, batch_size=1024, shuffle=True)

In [15]:
criterion = torch.nn.MSELoss()    
for inputs, targets in train_dataloader:
    inputs = inputs.reshape([-1, 1, 100, 100])
    outputs = net(inputs)
    print(outputs, targets)
    break

tensor([[0.0223],
        [0.0224],
        [0.0197],
        ...,
        [0.0269],
        [0.0275],
        [0.0287]], grad_fn=<AddmmBackward>) tensor([ 0.2778,  0.2222,  0.2778,  ...,  0.3333, -0.2778,  0.0000])


In [11]:
data.Xtrain

array([[ 0.22941178,  0.22549021,  0.22156864, ...,  0.33137256,
         0.03333336,  0.14313728],
       [ 0.21764708,  0.21764708,  0.22941178, ...,  0.33529413,
         0.0411765 ,  0.13137257],
       [ 0.2019608 ,  0.18627453,  0.21764708, ...,  0.33137256,
         0.03333336,  0.15098041],
       ...,
       [-0.327451  , -0.30392158, -0.27254903, ..., -0.30392158,
        -0.34313726, -0.37058824],
       [-0.31176472, -0.3       , -0.2647059 , ..., -0.33137256,
        -0.30784315, -0.22941175],
       [-0.2490196 , -0.22156861, -0.2529412 , ..., -0.3627451 ,
        -0.36666667, -0.31176472]], dtype=float32)

In [16]:
net.fc3.weight

Parameter containing:
tensor([[-0.0604, -0.0537, -0.0264,  ...,  0.0014, -0.0628, -0.0260]],
       requires_grad=True)